kurentoUrl: "ws://rluo-kurento.blindside-dev.com/kurento"
kurentoIp: "192.168.23.11"
localIpAddress: "192.168.23.11"
acceptSelfSignedCertificate: true
redisHost : "127.0.0.1"
redisPort : "6379"
minVideoPort: 30000
maxVideoPort: 33000
